### PR TITLE
streamlined template

### PR DESCRIPTION
**Pull request by cheesebroccoli**
Before issuing a pull request, please see the contributing page.

### CODE REVIEW

**Review by torinriley — COMMENTED** [review]
Elbow arm? as far I know we don't have an elbow arm.

**Comment by cheesebroccoli** [comment]
So I’m thinking about the future?

**Comment by torinriley** [comment]
Ok so we're planning on having an elbow arm in the future?

**Comment by cheesebroccoli** [comment]
Girl no

**Comment by torinriley** [comment]
Thenn why do we have code for it?

**Review by torinriley — APPROVED** [review]
The other changes look good though

**Comment by cheesebroccoli** [comment]
In case the team ever wants to add it in the future, I added it because
it’s for any 2 motor arm. Just delete if you dont want it there

**Pull request merged**
